site_name: "Aleksandr Lesnitsky - Portfolio"
site_url: https://fafakaj.github.io/
site_author: "Aleksandr Lesnitsky"

theme:
  name: dracula
  highlightjs: true
  hljs_style: dracula
  hljs_languages:
    - yaml
    - python
    - bash
    - javascript
    - html
    - css


nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
    - Список работ: labs/index.md
    - Лаба 1: labs/lab1.md
    - Лаба 2: labs/lab2.md
  - Проекты: projects.md
  - Контакты: contact.md